version: 2.1

orbs:
  slack-notifier: svinstech/slack-notifier-orb@1

commands:
  install-packages:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  ipc-tests:
    resource_class: svinstech/dev # Here, we use Vouch's self-hosted runner so the can gain network access.
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - install-packages
      - run:
          name: Set up environment variable(s)
          command: |
            touch .env
            echo "GITHUB_API_TOKEN=$GITHUB_API_TOKEN" >> .env
            echo "ENV=Stg" >> .env
      - run:
          name: Run IPC Health tests
          command: yarn run test:health
      - run:
          name: Run IPC Jurisdiction tests
          command: yarn run test:jurisdictions
      - run:
          name: Run IPC Jurisdiction Version tests
          command: yarn run test:jurisdictionVersions
      - run:
          name: Run IPC Product Lines tests
          command: yarn run test:productLines
      - slack-notifier/build-status-notification: 
          header: "Insurance Product Core Tests"
          channel-webhook-environment-variables: WEBHOOK_KELLEN_KINCAID

workflows:
  ipc-tests-workflow:
    jobs:
      - ipc-tests
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 4 * * 3" # Every Wednesday at midnight EST (4am UTC)
          filters:
            branches:
              only:
                - main
    jobs:
      - ipc-tests